import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Montserrat } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AosProvider from "@/Provider/AosProvider/AosProvider";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
import QueryProvider from "@/Provider/QueryProvider/QueryProvider";

// Fonts
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "JohnDox",
  description: "Generated by create next app",
  icons: {
    icon: "https://i.ibb.co.com/2YMddrBt/Group-1321314777.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <GoogleOAuthProvider clientId="841975640697-u4amnqfefa6ndr8rvijlbfpu3qovsgur.apps.googleusercontent.com">
          <QueryProvider>
            <AuthProvider>
              <AosProvider>
                <Toaster />
                {children}
              </AosProvider>
              <Toaster />
            </AuthProvider>
          </QueryProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
